OUTPUT_NAME=ixln
BUILD_STATIC_LIB = 1

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.settings

# include the basic rules for creation this module
include ../../../Impl/Make/Makefile.rules
