//*****************************************************************************************
// Move VC projects generated by qmake to sibling directory (eg. from QMake to VC9).
// Additionaly copied files will be corrected to privide correct functionality with ACF structures.
//*****************************************************************************************
var qmakeDirName = "QMake"
var projectExt = "vcproj";
var projectExp = new RegExp(".*\." + projectExt + "$");
var projectNewExt = "vcxproj";
var projectNewExp = new RegExp(".*\." + projectNewExt);
var solutionExt = "sln";
var solutionExp = new RegExp(".*\." + solutionExt + "$");
var projectTagExp = new RegExp("^Project.*");


function relativePath(base, rel) {
    var basel = base.split('\\');
    var rell = rel.split('\\');

    for (var i = basel.length; i-- >= 0; ) {
        if (basel[i] === '.')
            basel.splice(i, 1);
    }
    for (var i = basel.length; i-- >= 1; ) {
        if (basel[i] === '')
            basel.splice(i, 1);
    }
    for (var i = rell.length; i-- >= 0; ) {
        if (rell[i] === '.')
            rell.splice(i, 1);
    }
    for (var i = rell.length; i-- >= 1; ) {
        if (rell[i] === '')
            rell.splice(i, 1);
    }

    i = 0;
    while (i < basel.length && i < rell.length && basel[i] === rell[i])
        i++;

    var j = i;
    var r = [];

	var useAbsolutePath = (i == 0) && (rell.length > 0) && (rell[0] == "" || (rell[0].search(":") >= 0));

    if (!useAbsolutePath) {
        for (; i < basel.length; i++)
            r.push('..');
    }

    for (; j < rell.length; j++)
        r.push(rell[j]);

    return r.join('\\');
}

function ProcessFolder(shell, fileSystem, folder, vcDirName, replaceDirs) {
    var retVal = new String;

    for (var subFolderIter = new Enumerator(folder.SubFolders); !subFolderIter.atEnd() ; subFolderIter.moveNext()) {
        var subfolder = subFolderIter.item();
        if (subfolder.Name == qmakeDirName) {
            var destDir = folder + "\\" + vcDirName;
            if (!fileSystem.FolderExists(destDir)) {
                fileSystem.CreateFolder(destDir);
            }

            for (var fileIter = new Enumerator(subfolder.files); !fileIter.atEnd() ; fileIter.moveNext()) {
                var file = fileIter.item();

                if (projectExp.exec(file.Name) || projectNewExp.exec(file.Name)) {
                    // Move project to destination dir
                    var outputPath = destDir + "\\" + file.Name;

                    if (fileSystem.FileExists(outputPath)) {
                        fileSystem.DeleteFile(outputPath);
                    }

                    var inputFile = fileSystem.OpenTextFile(file, 1);
                    var outputFile = fileSystem.OpenTextFile(outputPath, 2, true);
					
                    while (!inputFile.AtEndOfStream) {
                        var text = inputFile.ReadLine();
                        var re1 = /IntermediateDirectory=\"release\\\"/g;
                        text = text.replace(re1, "InheritedPropertySheets=\"..\\..\\..\\Config\\" + vcDirName + "\\General.vsprops;..\\..\\..\\Config\\" + vcDirName + "\\Release.vsprops\"");

                        var re2 = /IntermediateDirectory=\"debug\\\"/g;
                        text = text.replace(re2, "InheritedPropertySheets=\"..\\..\\..\\Config\\" + vcDirName + "\\General.vsprops;..\\..\\..\\Config\\" + vcDirName + "\\Debug.vsprops\"");

                        for (var replFolderIter = new Enumerator(replaceDirs) ; !replFolderIter.atEnd() ; replFolderIter.moveNext()) {
                            var repl = replFolderIter.item();
                            if (repl.key != "") {
                                text = text.split(repl.key).join(repl.value);
                            }
                        }

						if (text == "</Project>"){
                          outputFile.WriteLine("  <ProjectExtensions>");
                          outputFile.WriteLine("    <VisualStudio>");
						  outputFile.WriteLine("      <UserProperties Qt5Version_x0020_Win32=\"$(DefaultQtVersion)\" />");
                          outputFile.WriteLine("    </VisualStudio>");
                          outputFile.WriteLine("  </ProjectExtensions>");
                        }

                        outputFile.WriteLine(text);
                    }

                    inputFile.close();

                    fileSystem.DeleteFile(file);
                }
                else if (solutionExp.exec(file.Name)) {
                    // Move corrected solution to destination dir
                    var outputPath = destDir + "\\" + file.Name;

                    if (fileSystem.FileExists(outputPath)) {
                        fileSystem.DeleteFile(outputPath);
                    }

                    var inputFile = fileSystem.OpenTextFile(file, 1);
                    var outputFile = fileSystem.OpenTextFile(outputPath, 2, true);
					
					while (!inputFile.AtEndOfStream){
						var text = inputFile.ReadLine();
						var re1 = /QMake/g;
						text = text.replace(re1, vcDirName);
						
						if (projectTagExp.exec(text)){
							var textParts = text.split('", "');
							
							textParts[1] = relativePath(destDir, textParts[1].split('/').join('\\'));

							text = textParts.join("\", \"");
						}

						outputFile.WriteLine(text);
					}

					inputFile.close();

                    fileSystem.DeleteFile(file);
				}
            }

            // Copy directories for Qt generated files
            if (fileSystem.FolderExists(subfolder + "\\debug")) {
                if (fileSystem.FolderExists(destDir + "\\Debug")) {
                    fileSystem.DeleteFolder(subfolder + "\\debug");
                }
                else {
                    fileSystem.MoveFolder(subfolder + "\\debug", destDir + "\\Debug");
                }
            }
            if (fileSystem.FolderExists(subfolder + "\\release")) {
                if (fileSystem.FolderExists(destDir + "\\Release")) {
                    fileSystem.DeleteFolder(subfolder + "\\release");
                }
                else {
                    fileSystem.MoveFolder(subfolder + "\\release", destDir + "\\Release");
                }
            }
        }
        else {
            ProcessFolder(shell, fileSystem, subfolder, vcDirName, replaceDirs);
        }
    }
}


var fileSystem = WScript.CreateObject("Scripting.FileSystemObject");
var shell = WScript.CreateObject("WScript.Shell");

if (WScript.Arguments.length >= 1) {
    var vcDirName = WScript.Arguments(0).toString();

    var replaceDirs = [];
    replaceDirs.push({ key: shell.ExpandEnvironmentStrings("%QTDIR%"), value: "$(QTDIR)" });
    replaceDirs.push({ key: shell.ExpandEnvironmentStrings("%QTDIR%").split("\\").join("/"), value: "$(QTDIR)" });
    replaceDirs.push({ key: shell.ExpandEnvironmentStrings("%ACFDIR%"), value: "$(ACFDIR)" });
    replaceDirs.push({ key: shell.ExpandEnvironmentStrings("%ACFDIR%").split("\\").join("/"), value: "$(ACFDIR)" });

    ProcessFolder(shell, fileSystem, fileSystem.GetFolder("."), vcDirName, replaceDirs);
}
