OUTPUT_NAME=iqsci
BUILD_STATIC_LIB = 1

# include the definitions for Qt compilation
include ../../../Impl/Make/MakefileQt.rules

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.rules
