/********************************************************************************
**
**	Copyright (c) Kirill Lepski and Witold Gantzke
**	All rights reserved.
**	
**	Permission is granted to copy, distribute and/or modify this document 
**	under the terms of the GNU Free Documentation License, Version 1.2 
**	or any later version published by the Free Software Foundation; 
**	A copy of the license is included in the file GNU.txt.
**
** 	See http://www.imagingtools.de or email info@imagingtools.de for further
** 	information about the ACF.
********************************************************************************/


OUTPUT_NAME=iqsci

# include the definitions for Qt compilation
include ../../../Impl/Make/MakefileQt.rules

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.rules
