LIBRARY_NAME=iqsci

# include the definitions for Qt compilation
include ../../../Impl/make/MakefileQt.rules

# include the basic definitions for this module
include ../../../Impl/make/Makefile.rules
