OUTPUT_NAME=ibase

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.settings

# include the basic rules for creation this module
include ../../../Impl/Make/Makefile.rules
