// SPDX-License-Identifier: LGPL-2.1-or-later OR GPL-2.0-or-later OR GPL-3.0-or-later OR LicenseRef-ACF-Commercial
#pragma once


// Qt inclides
#include <QtCore/QFile>

// ACF includes
#include <iser/CJsonReadArchiveBase.h>


namespace ifile
{


class CJsonFileReadArchive: public iser::CJsonReadArchiveBase
{
public:
	/**
		Message IDs generated by this archive.
	*/
	enum MessageId
	{
		MI_FILE_OPEN_ERROR = 0x3f320c0
	};

	typedef iser::CJsonReadArchiveBase BaseClass;

	CJsonFileReadArchive(const QString& filePath = "", bool serializeHeader = true);

	bool OpenFile(const QString& filePath);
	bool IsOpen() const override;

protected:
	// reimplemented (istd::ILogger)
	virtual void DecorateMessage(
				istd::IInformationProvider::InformationCategory category,
				int id,
				int flags,
				QString& message,
				QString& messageSource) const override;

private:
	QFile m_file;
};


} // namespace ifile
