string(FIND "$ENV{ARXCHOST}" "VC" POSITION_OF_VC)
if (WIN32 OR (${POSITION_OF_VC} EQUAL 0))
	set(ARX_COMPILER "Arxc.exe")
	set(ACF_TOOL "Acf.exe")
	set(QMAKE_RCC "rcc.exe")
	set(COPY_FILE "copy")
	set(QMAKE_LRELEASE "lrelease.exe")
else()
	set(ARX_COMPILER "Arxc")
	set(ACF_TOOL "Acf")
	set(QMAKE_RCC "rcc")
	set(COPY_FILE "cp")
	set(QMAKE_LRELEASE "lrelease")
endif()

if (APPLE)
	set(ARX_COMPILER "Arxc.app/Contents/MacOS/Arxc")
	set(ACF_TOOL "Acf.app/Contents/MacOS/Acf")
endif()

set(PROJECT_BINARY_DIR ${AUX_INCLUDE_DIR}/${PROJECT_NAME})

if(NOT DEFINED ACFDIR_BUILD)
	if(DEFINED ENV{ACFDIR_BUILD})
		set(ACFDIR_BUILD $ENV{ACFDIR_BUILD})
	else()
		if(NOT DEFINED BUILDDIR)
			set(ACFDIR_BUILD ${BUILDDIR}/Acf)
		else()
			set(ACFDIR_BUILD ${ACFDIR})
		endif()
	endif()
endif()

message(VERBOSE "ACFDIR_BUILD ${ACFDIR_BUILD}")

get_filename_component(ARXC_FILES_NAME "${ARXC_FILES}" NAME_WE)

set(ARXC_OUTFILE_NAME C${ARXC_FILES_NAME}.cpp)

set(HEADER_FILE_AUX "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/C${ARXC_FILES_NAME}.h")
set(SOURCES_FILE_AUX "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/C${ARXC_FILES_NAME}.cpp")

if(ANDROID)
	set(ARXCBIN "${ACFDIR_BUILD}/Bin/${CMAKE_BUILD_TYPE}_$ENV{ARXCHOST}/${ARX_COMPILER}")
	set(ACFBIN "${ACFDIR_BUILD}/Acf/Bin/${CMAKE_BUILD_TYPE}_$ENV{ARXCHOST}/${ACF_TOOL}")
	set(ARXC_OUTFILE_NAME ${PROJECT_BINARY_DIR}/C${ARXC_FILES_NAME}.cpp)
else()
	set(ARXCBIN "${ACFDIR_BUILD}/Bin/${CMAKE_BUILD_TYPE}_${TARGETNAME}/${ARX_COMPILER}")
	set(ACFBIN "${ACFDIR_BUILD}/Bin/${CMAKE_BUILD_TYPE}_${TARGETNAME}/${ACF_TOOL}")
endif()

# collecting additional deps for ARX
set(ARX_DEPS_LIST)
if(ARXC_CONFIG AND (ARX_ENABLE_GENERATE_DEPENDENCIES_LIST OR NOT DEFINED ARX_ENABLE_GENERATE_DEPENDENCIES_LIST))
	set(ARX_DEPS_FILE_PATH "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/ArxDependsList.txt")
	set(ARX_ERRORS_FILE_PATH "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/ArxDependsList_errors.txt")

	message(STAUTS "Collecting ARX dependences for ${PROJECT_NAME}")
	
	execute_process(
		COMMAND
		    ${ARXCBIN} ${ARXC_FILES} -mode depends -config ${ARXC_CONFIG} -conf_name ${CMAKE_BUILD_TYPE}_${TARGETNAME} -env_vars ${ENV_VARS}
		OUTPUT_FILE
		    ${ARX_DEPS_FILE_PATH}
		ERROR_FILE
		    ${ARX_ERRORS_FILE_PATH}
		RESULT_VARIABLE
		    ARX_DEPS_GENERATION_RESULT_CODE
	)

	if(NOT ARX_DEPS_GENERATION_RESULT_CODE EQUAL 0)
		message("!!! ARX Cannot to create dependens")

		file(STRINGS ${ARX_DEPS_FILE_PATH} ERRORS1_ARX_DEPS_LIST)
		message("${ERRORS1_ARX_DEPS_LIST}")

		file(STRINGS ${ARX_ERRORS_FILE_PATH} ERRORS2_ARX_DEPS_LIST)
		message("${ERRORS2_ARX_DEPS_LIST}")

		execute_process(
			COMMAND
				${ARXCBIN} ${ARXC_FILES} -mode depends -config ${ARXC_CONFIG} -conf_name ${CMAKE_BUILD_TYPE}_${TARGETNAME} -v -env_vars ${ENV_VARS}
		)
		message("${ARXCBIN} ${ARXC_FILES} -mode depends -config ${ARXC_CONFIG} -conf_name ${CMAKE_BUILD_TYPE}_${TARGETNAME} -env_vars ${ENV_VARS}")
		message(FATAL_ERROR "!!! ARX finished unexpected. Error code: [${ARX_DEPS_GENERATION_RESULT_CODE}]")
	endif()

	file(STRINGS ${ARX_DEPS_FILE_PATH} ARX_DEPS_LIST)
endif()

add_custom_command(OUTPUT "${HEADER_FILE_AUX}" "${SOURCES_FILE_AUX}"
	COMMAND
		${ARXCBIN}
	ARGS
		${ARXC_FILES} -o ${ARXC_OUTFILE_NAME} -config ${ARXC_CONFIG} -conf_name ${CMAKE_BUILD_TYPE}_${TARGETNAME} -env_vars ${ENV_VARS} -v
	WORKING_DIRECTORY
		"${AUX_INCLUDE_DIR}/${PROJECT_NAME}"
	DEPENDS
		${ARXCBIN} ${ARXC_FILES} ${ARX_DEPS_LIST}
	VERBATIM)


if(WIN32)
	if(ACF_CONVERT_FILES)
		set(RC_FILE "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/${PROJECT_NAME}.rc")
		set(RC_COMPILE_FILE "${AUX_INCLUDE_DIR}/${PROJECT_NAME}/${PROJECT_NAME}.res")
		list(APPEND ARX_DEPS_LIST ${DEPS_CUSTOM_BUILD})

		add_custom_command(
			OUTPUT ${RC_FILE}
			COMMAND ${ACFBIN}
			ARGS ${ACF_CONVERT_REGISTRY} -console -config ${ACF_CONVERT_CONFIG} -input ${ACF_CONVERT_FILES} -o ${RC_FILE} -env_vars ${ENV_VARS}
			COMMENT "Start convert ${PROJECT_NAME}.rc"
			DEPENDS ${ACFBIN} ${ACF_CONVERT_FILES} ${ARX_DEPS_LIST} VERBATIM)
		add_custom_target(CONVERT_FILES${PROJECT_NAME} ALL DEPENDS ${RC_FILE})

		message("RES CONVERT ${ACFBIN} ${ACF_CONVERT_REGISTRY} -console -config ${ACF_CONVERT_CONFIG} -input ${ACF_CONVERT_FILES} -o ${RC_FILE} -env_vars ${ENV_VARS}")

		add_custom_command(
			OUTPUT ${RC_COMPILE_FILE}
			COMMAND ${CMAKE_RC_COMPILER} ${RC_FILE}
			WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
			COMMENT "Start ${PROJECT_NAME}.rc compiler"
			DEPENDS ${RC_FILE} ${ARX_DEPS_LIST} VERBATIM)
		add_custom_target(COMPILE_RES${PROJECT_NAME} ALL DEPENDS ${RC_COMPILE_FILE})

	endif()
endif()


if(ACF_TRANSLATIONS)
	add_custom_command(OUTPUT ${TRANSLATION_OUTPUT_FILE}
		COMMAND ${QMAKE_LRELEASE}
		ARGS ${ACF_TRANSLATIONS} -qm ${TRANSLATION_OUTPUT_FILE}
		DEPENDS ${ACF_TRANSLATIONS})
	add_custom_target(LRELEASE${PROJECT_NAME} ALL DEPENDS ${TRANSLATION_OUTPUT_FILE})
endif()

set_property(SOURCE ${SOURCES_FILE_AUX} PROPERTY SKIP_AUTOMOC ON)
set_property(SOURCE ${HEADER_FILE_AUX} PROPERTY SKIP_AUTOMOC ON)

