#General base configuration should be included from all ACF-based projects

message("PROJECT_NAME " ${PROJECT_NAME})
message("CMAKE_CURRENT_LIST_DIR " ${CMAKE_CURRENT_LIST_DIR})
message("PROJECT_SOURCE_DIR " ${PROJECT_SOURCE_DIR})
message("BINARY_DIR " ${BINARY_DIR})

#add_compile_options(-fno-rtti)
#add_compile_options(-msse2)

#set(PLATFORM_CODE i86)

#if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL "X64")
#set(PLATFORM_CODE x64)
#endif()

set(COMPILER_NAME "CLang")

if(${MSVC})
    set(COMPILER_NAME "VC")
#    #	add_compile_options(/W4)
    set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /wd4127 /wd4250 /wd4347 /wd4355 /wd4365 /wd4481 /wd4505 /wd4510 /wd4511 /wd4512 /wd4548 /wd4571 /wd4619 /wd4625 /wd4626 /wd4640 /wd4702 /wd4710 /wd4820 /wd4826")
	set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /MP /fp:fast")
	set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS")
	set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /bigobj")

#	# Qt-BUG 31516. Remove it after the fix in Qt!!!
#	set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /wd4718")
#	if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL x64)
#		set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /arch:SSE2")
#	endif()
#message("CMAKE_CXX_FLAGS " ${CMAKE_CXX_FLAGS})

    if(${MSVC_TOOLSET_VERSION} STREQUAL 80)
        #	message("Visual Studio 2005")
      #  set(COMPILER_NAME "VC8")
    endif()

    if(${MSVC_TOOLSET_VERSION} STREQUAL 90)
        #	message("Visual Studio 2008")
      #  set(COMPILER_NAME "VC9")
        string(REPLACE "/Gd" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
        string(REPLACE "/GD" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
        string(REPLACE "-Gd" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
        string(REPLACE "-GD" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
    endif()

    if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
        #	message("Visual Studio 2010")
     #   set(COMPILER_NAME "VC10")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4996")
    endif()

    if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
        #	message("Visual Studio 2012")
       # set(COMPILER_NAME "VC11")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4996")
    endif()

    if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
        #	message("Visual Studio 2013")
      #  set(COMPILER_NAME "VC12")
        add_compile_options(-std=c++11)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4996 /Qpar /Gy /Gw /FS")
    endif()

    if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
        #	message("Visual Studio 2015")
      #  set(COMPILER_NAME "VC14")
        set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /Qpar /Gy /Gw /FS /Zc:threadSafeInit-")
        set(CMAKE_CXX_FLAGS_RELEASE_INIT "${CMAKE_CXX_FLAGS_RELEASE_INIT} /Ot /Oi /Ob2 /GS-")
		if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL x64)
            set(CMAKE_CXX_LINK_LIBRARY_FLAG "${CMAKE_CXX_LINK_LIBRARY_FLAG} /MACHINE:X64")
        endif()
    endif()
    if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
#		    message("Visual Studio 2017")
       # set(COMPILER_NAME "VC15")
		set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /Qpar /Gy /Gw /FS /Zc:threadSafeInit-")
		set(CMAKE_CXX_FLAGS_RELEASE_INIT "${CMAKE_CXX_FLAGS_RELEASE_INIT} /Ot /Oi /Ob2 /GS-")
		#if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL x64)
		#	set(CMAKE_CXX_LINK_LIBRARY_FLAG "${CMAKE_CXX_LINK_LIBRARY_FLAG} /MACHINE:X64")
		#	message("CMAKE_CXX_LINK_LIBRARY_FLAG " ${CMAKE_CXX_LINK_LIBRARY_FLAG})
		#endif()
    endif()
    if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
        #	message("Visual Studio 2019")
       # set(COMPILER_NAME "VC16")
        set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} /Qpar /Gy /Gw /FS /Zc:threadSafeInit-")
        set(CMAKE_CXX_FLAGS_RELEASE_INIT "${CMAKE_CXX_FLAGS_RELEASE_INIT} /Ot /Oi /Ob2 /GS-")
		#if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL x64)
		    #set(CMAKE_CXX_LINK_LIBRARY_FLAG "${CMAKE_CXX_LINK_LIBRARY_FLAG} /MACHINE:X64")
			#endif()
    endif()
#	if(${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} STREQUAL X86)
#        set(COMPILER_NAME "${COMPILER_NAME}_64")
#    endif()
#    if(${CMAKE_CL_64} STREQUAL 1)
#		set(COMPILER_NAME "${COMPILER_NAME}_64")
#	endif()

endif()

message("CMAKE_CXX_COMPILER_ARCHITECTURE_ID " "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")


#set(COMPILER_DIR "${CMAKE_BUILD_TYPE}${COMPILER_NAME}${PLATFORM_CODE}")

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(AUXINCLUDEDIR "AuxInclude/Qt${QT_VERSION_MAJOR}_${TARGETNAME}/GeneratedFiles")
set(AUXINCLUDEPATH "${PROJECT_SOURCE_DIR}/../../../${AUXINCLUDEDIR}")
set(ACF_TRANSLATIONS_OUTDIR "${AUXINCLUDEPATH}/${TARGETNAME}")
#set(AUTOGEN_BUILD_DIR "${ACF_TRANSLATIONS_OUTDIR}")

#set(CMAKE_AUTOMOC ON)
#set(CMAKE_AUTORCC ON)
#set(CMAKE_AUTOUIC ON)

find_package("Qt${QT_VERSION_MAJOR}" COMPONENTS Core Widgets Core Gui Xml Network XmlPatterns Svg Concurrent REQUIRED)

include_directories("${PROJECT_SOURCE_DIR}/../../")

include_directories("${INCLUDE_DIR}")
include_directories("${IMPL_DIR}")


function(acf_create_moc outfiles)
        if(QT_VERSION_MAJOR EQUAL 5)
		qt5_wrap_cpp("${outfiles}" ${ARGN} )
        elseif(QT_VERSION_MAJOR EQUAL 6)
		qt6_wrap_cpp("${outfiles}" ${ARGN} )
	endif()
	set("${outfiles}" "${${outfiles}}" PARENT_SCOPE)
endfunction()

function(acf_wrap_resources outfiles)
        if(QT_VERSION_MAJOR EQUAL 5)
		qt5_add_resources("${outfiles}" ${ARGN})
        elseif(QT_VERSION_MAJOR EQUAL 6)
		qt6_add_resources("${outfiles}" ${ARGN})
	endif()
	set("${outfiles}" "${${outfiles}}" PARENT_SCOPE)
endfunction()

function(acf_wrap_ui outfiles)
        if(QT_VERSION_MAJOR EQUAL 5)
		qt5_wrap_ui("${outfiles}" ${ARGN})
        elseif(QT_VERSION_MAJOR EQUAL 6)
		qt6_wrap_ui("${outfiles}" ${ARGN})
	endif()
	set("${outfiles}" "${${outfiles}}" PARENT_SCOPE)
endfunction()

if(${MSVC})
	#link_libraries("C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/Mpr.lib")
   link_libraries("Mpr.lib")
endif()
