macro(subdirlist result curdir)
	file(GLOB children RELATIVE ${curdir} ${curdir}/*)
	set(dirlist "")
	foreach(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child})
			LIST(APPEND dirlist ${child})
		ENDIF()
	endforeach()
	set(${result} ${dirlist})
endmacro()

macro(get_target_name target_name)
    set(COMPILER_NAME "Clang")
    if(${MSVC})
        if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
            set(COMPILER_NAME "VC10")
        endif()
        if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
            set(COMPILER_NAME "VC11")
        endif()

        if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
            set(COMPILER_NAME}"VC12")
        endif()

        if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
            set(COMPILER_NAME "VC14")
        endif()
        if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
            set(COMPILER_NAME "VC15")
        endif()
        if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
            set(COMPILER_NAME "VC16")
        endif()

		if(${CMAKE_CL_64} STREQUAL 1)
			set(COMPILER_NAME "${COMPILER_NAME}_64")
		endif()
	else()
		set(COMPILER_NAME "${COMPILER_NAME}_64")
	endif()

	message("CMAKE_CXX_COMPILER_ARCHITECTURE_ID " "${CMAKE_CL_64}")


	set(${target_name} "${COMPILER_NAME}")
endmacro()
