macro(subdirlist result curdir)
	file(GLOB children RELATIVE ${curdir} ${curdir}/*)
	set(dirlist "")
	foreach(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child})
		LIST(APPEND dirlist ${child})
		ENDIF()
	endforeach()
	set(${result} ${dirlist})
endmacro()

macro(acf_define_link_scope_var VAR_NAME DEFAULT_VALUE DOC_STRING)
	set(${VAR_NAME} "${DEFAULT_VALUE}" CACHE STRING "${DOC_STRING}. Valid values are: '', PUBLIC, PRIVATE, INTERFACE")
	set_property(CACHE ${VAR_NAME} PROPERTY STRINGS "" "PUBLIC" "PRIVATE" "INTERFACE")
	if(NOT "${${VAR_NAME}}" STREQUAL "" AND NOT "${${VAR_NAME}}" MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
		message(FATAL_ERROR "${VAR_NAME} must be one of: '', PUBLIC, PRIVATE, INTERFACE (got: ${${VAR_NAME}})")
	endif()
endmacro()

if(NOT COMMAND acf_declare_target_dependencies)
	function(acf_declare_target_dependencies target)
		cmake_parse_arguments(ARG "" "LINK_SCOPE" "" ${ARGN})

		# When callers pass LINK_SCOPE ${SOME_SCOPE_VAR} and the variable is empty,
		# CMake shifts the first dependency token into LINK_SCOPE. Recover by
		# treating unknown scope values as dependencies.
		if(ARG_LINK_SCOPE)
			string(TOUPPER "${ARG_LINK_SCOPE}" _acf_dep_scope_candidate)
			if(NOT _acf_dep_scope_candidate MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
				list(INSERT ARG_UNPARSED_ARGUMENTS 0 "${ARG_LINK_SCOPE}")
				unset(ARG_LINK_SCOPE)
			endif()
		endif()

		if(NOT ARG_LINK_SCOPE)
			if(DEFINED ACF_LIBRARY_LINK_SCOPE AND NOT "${ACF_LIBRARY_LINK_SCOPE}" STREQUAL "")
				set(ARG_LINK_SCOPE ${ACF_LIBRARY_LINK_SCOPE})
			else()
				set(ARG_LINK_SCOPE PUBLIC)
			endif()
		endif()

		if(NOT TARGET ${target})
			return()
		endif()

		# target_link_libraries() is illegal on ALIAS targets, and can also conflict
		# with old plain-signature calls from legacy helper templates.
		# Apply dependencies via target properties to keep behavior deterministic.
		get_target_property(_acf_dep_aliased ${target} ALIASED_TARGET)
		if(_acf_dep_aliased)
			return()
		endif()

		string(TOUPPER "${ARG_LINK_SCOPE}" _acf_dep_scope)
		get_target_property(_acf_dep_imported ${target} IMPORTED)
		get_target_property(_acf_dep_type ${target} TYPE)

		foreach(dependency IN LISTS ARG_UNPARSED_ARGUMENTS)
			if(TARGET ${dependency})
				if(_acf_dep_imported)
					set_property(TARGET ${target} APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${dependency})
				elseif(_acf_dep_type STREQUAL "INTERFACE_LIBRARY")
					set_property(TARGET ${target} APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${dependency})
				elseif(_acf_dep_scope STREQUAL "INTERFACE")
					set_property(TARGET ${target} APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${dependency})
				elseif(_acf_dep_scope STREQUAL "PUBLIC")
					set_property(TARGET ${target} APPEND PROPERTY LINK_LIBRARIES ${dependency})
					if(NOT _acf_dep_type STREQUAL "EXECUTABLE")
						set_property(TARGET ${target} APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${dependency})
					endif()
				else()
					set_property(TARGET ${target} APPEND PROPERTY LINK_LIBRARIES ${dependency})
				endif()
			endif()
		endforeach()
	endfunction()
endif()

macro(get_target_name target_name)
	set(COMPILER_NAME "Clang")
	if(${MSVC})
		if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
			set(COMPILER_NAME "VC10")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
			set(COMPILER_NAME "VC11")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
			set(COMPILER_NAME}"VC12")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
			set(COMPILER_NAME "VC14")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
			set(COMPILER_NAME "VC15")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
			set(COMPILER_NAME "VC16")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 143)
			set(COMPILER_NAME "VC17")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 144)
			set(COMPILER_NAME "VC18")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 145)
			set(COMPILER_NAME "VC18")
		endif()

		if(COMPILER_NAME STREQUAL "Clang")
			# Fallback for unrecognized MSVC toolset versions
			set(COMPILER_NAME "VC${MSVC_TOOLSET_VERSION}")
			message(WARNING "Unrecognized MSVC_TOOLSET_VERSION: ${MSVC_TOOLSET_VERSION}, using ${COMPILER_NAME}")
		endif()

		add_compile_definitions(COMPILER_NAME=${COMPILER_NAME})
		set(COMPILER_CODE "${COMPILER_NAME}")

		if(${CMAKE_CL_64} STREQUAL 1)
			set(COMPILER_CODE "${COMPILER_CODE}_x64")
			add_compile_definitions(PLATFORM_CODE=x64)
		else()
			add_compile_definitions(PLATFORM_CODE)
		endif()
	elseif(${ANDROID})
		set(COMPILER_CODE "ClangAndroid_${CMAKE_ANDROID_ARCH_ABI}")
		add_compile_definitions(COMPILER_NAME=ClangAndroid)
		add_compile_definitions(PLATFORM_CODE=${CMAKE_ANDROID_ARCH_ABI})
	elseif(${APPLE})

		if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
			set(COMPILER_CODE "${COMPILER_NAME}OSX_arm64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=arm64)
		else()
			set(COMPILER_CODE "${COMPILER_NAME}OSX_x64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=x64)
		endif()

	elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")

		if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set(COMPILER_CODE "GCCLinux_x64")
			add_compile_definitions(COMPILER_NAME=GCCLinux)
		else()
			set(COMPILER_CODE "ClangLinux_x64")
			add_compile_definitions(COMPILER_NAME=ClangLinux)
		endif()
		add_compile_definitions(PLATFORM_CODE=x64)
	endif()

	add_compile_definitions(ACF_QT_VERSION=Qt${QT_VERSION_MAJOR})

	set(${target_name} "Qt${QT_VERSION_MAJOR}_${COMPILER_CODE}")
endmacro()
