macro(subdirlist result curdir)
	file(GLOB children RELATIVE ${curdir} ${curdir}/*)
	set(dirlist "")
	foreach(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child})
		LIST(APPEND dirlist ${child})
		ENDIF()
	endforeach()
	set(${result} ${dirlist})
endmacro()

macro(get_target_name target_name)
	set(COMPILER_NAME "Clang")
	if(${MSVC})
		if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
			set(COMPILER_NAME "VC10")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
			set(COMPILER_NAME "VC11")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
			set(COMPILER_NAME}"VC12")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
			set(COMPILER_NAME "VC14")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
			set(COMPILER_NAME "VC15")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
			set(COMPILER_NAME "VC16")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 143)
			set(COMPILER_NAME "VC17")
		endif()

		add_compile_definitions(COMPILER_NAME=${COMPILER_NAME})
		set(COMPILER_CODE "${COMPILER_NAME}")

		if(${CMAKE_CL_64} STREQUAL 1)
			set(COMPILER_CODE "${COMPILER_CODE}_x64")
			add_compile_definitions(PLATFORM_CODE=x64)
		else()
			add_compile_definitions(PLATFORM_CODE)
		endif()
	elseif(${ANDROID})
		set(COMPILER_CODE "ClangAndroid_${CMAKE_ANDROID_ARCH_ABI}")
		add_compile_definitions(COMPILER_NAME=ClangAndroid)
		add_compile_definitions(PLATFORM_CODE=${CMAKE_ANDROID_ARCH_ABI})
	elseif(${APPLE})

		if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
			set(COMPILER_CODE "${COMPILER_NAME}OSX_arm64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=arm64)
		else()
			set(COMPILER_CODE "${COMPILER_NAME}OSX_x64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=x64)
		endif()

	elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")

		if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set(COMPILER_CODE "GCCLinux_x64")
			add_compile_definitions(COMPILER_NAME=GCCLinux)
		else()
			set(COMPILER_CODE "ClangLinux_x64")
			add_compile_definitions(COMPILER_NAME=ClangLinux)
		endif()
		add_compile_definitions(PLATFORM_CODE=x64)
	endif()

	add_compile_definitions(ACF_QT_VERSION=Qt${QT_VERSION_MAJOR})

	set(${target_name} "Qt${QT_VERSION_MAJOR}_${COMPILER_CODE}")
endmacro()
