macro(subdirlist result curdir)
	file(GLOB children RELATIVE ${curdir} ${curdir}/*)
	set(dirlist "")
	foreach(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child})
		LIST(APPEND dirlist ${child})
		ENDIF()
	endforeach()
	set(${result} ${dirlist})
endmacro()

macro(define_link_scope_var VAR_NAME DEFAULT_VALUE DOC_STRING)
	set(${VAR_NAME} "${DEFAULT_VALUE}" CACHE STRING "${DOC_STRING}. Valid values are: '', PUBLIC, PRIVATE, INTERFACE")
	set_property(CACHE ${VAR_NAME} PROPERTY STRINGS "" "PUBLIC" "PRIVATE" "INTERFACE")
	if(NOT "${${VAR_NAME}}" STREQUAL "" AND NOT "${${VAR_NAME}}" MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
		message(FATAL_ERROR "${VAR_NAME} must be one of: '', PUBLIC, PRIVATE, INTERFACE (got: ${${VAR_NAME}})")
	endif()
endmacro()

function(declare_target_dependencies target)
	cmake_parse_arguments(ARG "" "LINK_SCOPE" "" ${ARGN})

	if(NOT ARG_LINK_SCOPE)
		set(ARG_LINK_SCOPE ${ACF_LIBRARY_LINK_SCOPE})
	endif()

	if(NOT TARGET ${target})
		return()
	endif()

	foreach(dependency IN LISTS ARG_UNPARSED_ARGUMENTS)
		if(TARGET ${dependency})
			target_link_libraries(${target} ${ARG_LINK_SCOPE} ${dependency})
		endif()
	endforeach()
endfunction()

macro(get_target_name target_name)
	set(COMPILER_NAME "Clang")
	if(${MSVC})
		if(${MSVC_TOOLSET_VERSION} STREQUAL 100)
			set(COMPILER_NAME "VC10")
		endif()
		if(${MSVC_TOOLSET_VERSION} STREQUAL 110)
			set(COMPILER_NAME "VC11")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 120)
			set(COMPILER_NAME}"VC12")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 140)
			set(COMPILER_NAME "VC14")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 141)
			set(COMPILER_NAME "VC15")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 142)
			set(COMPILER_NAME "VC16")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 143)
			set(COMPILER_NAME "VC17")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 144)
			set(COMPILER_NAME "VC18")
		endif()

		if(${MSVC_TOOLSET_VERSION} STREQUAL 145)
			set(COMPILER_NAME "VC18")
		endif()

		if(COMPILER_NAME STREQUAL "Clang")
			# Fallback for unrecognized MSVC toolset versions
			set(COMPILER_NAME "VC${MSVC_TOOLSET_VERSION}")
			message(WARNING "Unrecognized MSVC_TOOLSET_VERSION: ${MSVC_TOOLSET_VERSION}, using ${COMPILER_NAME}")
		endif()

		add_compile_definitions(COMPILER_NAME=${COMPILER_NAME})
		set(COMPILER_CODE "${COMPILER_NAME}")

		if(${CMAKE_CL_64} STREQUAL 1)
			set(COMPILER_CODE "${COMPILER_CODE}_x64")
			add_compile_definitions(PLATFORM_CODE=x64)
		else()
			add_compile_definitions(PLATFORM_CODE)
		endif()
	elseif(${ANDROID})
		set(COMPILER_CODE "ClangAndroid_${CMAKE_ANDROID_ARCH_ABI}")
		add_compile_definitions(COMPILER_NAME=ClangAndroid)
		add_compile_definitions(PLATFORM_CODE=${CMAKE_ANDROID_ARCH_ABI})
	elseif(${APPLE})

		if("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "arm64")
			set(COMPILER_CODE "${COMPILER_NAME}OSX_arm64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=arm64)
		else()
			set(COMPILER_CODE "${COMPILER_NAME}OSX_x64")
			add_compile_definitions(COMPILER_NAME=ClangOSX)
			add_compile_definitions(PLATFORM_CODE=x64)
		endif()

	elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")

		if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set(COMPILER_CODE "GCCLinux_x64")
			add_compile_definitions(COMPILER_NAME=GCCLinux)
		else()
			set(COMPILER_CODE "ClangLinux_x64")
			add_compile_definitions(COMPILER_NAME=ClangLinux)
		endif()
		add_compile_definitions(PLATFORM_CODE=x64)
	endif()

	add_compile_definitions(ACF_QT_VERSION=Qt${QT_VERSION_MAJOR})

	set(${target_name} "Qt${QT_VERSION_MAJOR}_${COMPILER_CODE}")
endmacro()
