OUTPUT_NAME=idb
BUILD_STATIC_LIB = 1

HAS_CPP = 0

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.settings

# include the basic rules for creation this module
include ../../../Impl/Make/Makefile.rules
