#ifndef istd_CSystem_included
#define istd_CSystem_included


// Qt includes
#include <QtCore/QString>
#include <QtCore/QMap>


#if defined(Sleep)
#undef Sleep
#endif


namespace istd
{


/**
	Implementation of global system helpers.

	\ingroup SystemDefines
*/
class CSystem
{
public:
	typedef QMap<QString, QString> EnvironmentVariables;

	struct FileDriveInfo
	{
		FileDriveInfo()
			: totalBytes(0),
			freeBytes(0),
			isValid(false)
		{
		}

		bool operator ==(const FileDriveInfo& info) const
		{
			return (totalBytes == info.totalBytes) && (freeBytes == info.freeBytes) && (isValid == info.isValid);
		}

		quint64 totalBytes;
		quint64 freeBytes;
		bool isValid;
	};

	struct FileDriveDescriptor
	{
		FileDriveInfo info;
		QString name;
		QByteArray id;

		bool operator == (const FileDriveDescriptor& driveInfo) const
		{
			return (info == driveInfo.info) && (name == driveInfo.name) && (id == driveInfo.id);
		}
	};


	// static methods

	/**
		Get the name of the operation system currently used.
	*/
	static QString GetOperationSystemName();

	/**
		Make a valid file name from a string.
		All not allowed characters in the \c fileNameString will be replaced by a valid symbol defined in c\replacingChar or removed if this parameter is not set.
		\param fileNameString	Input string representing the file name
		\param fileName	Resulting file name if the conversion was successful.
		\return \c true if the operation was successful, otherwise \c false.
	*/
	static bool ConvertToFileName(const QString& fileNameString, QString& fileName, const QString replacingChar = QString());

	/**
		Get normalized path with enrolled system variables.
	*/
	static QString GetNormalizedPath(const QString& path);

	/**
		Get value of system variables.
		\param	varName	name of variable.
		\param	envVars	if enabled, the system environment variables will be also considered.
	*/
	static QString GetVariableValue(const QString& varName, bool envVars = true, bool embeddedVars = true);

	/**
		Get path with enrolled system variables.
	*/
	static QString GetEnrolledPath(const QString& path, bool envVars = true, bool embeddedVars = true);

	/**
		Get list of environment valiables related to the current process.
	*/
	static EnvironmentVariables GetEnvironmentVariables();

	/**
		Set path for for temporary data to the current process.
	*/
	static void SetTempDirectoryPath(const QString& tempPath);

	/**
		Sleep current thread.
	*/
	static void Sleep(double seconds);

	/** 
		Copy files and directories from one folder to another.
	*/
	static bool CopyDirectory(const QString &srcPath, const QString &dstPath);

	/**
		Remove a given directory with all contents.
	*/
	static bool RemoveDirectory(const QString& directoryPath);

	/**
		Copy file to directory. If the target directory doesn't exist, it will be created.
	*/
	static bool FileCopy(const QString& source, const QString& result, bool overWrite = false);

	/**
		Move a file to another directory. If the target directory doesn't exist, it will be created.
	*/
	static bool FileMove(const QString& source, const QString& targetFolder, bool overWrite = false);

	/**
		Ensure that the given path exists.
	*/
	static bool EnsurePathExists(const QString& filePath);

	/**
		Get the name of the currently logged user.
	*/
	static QString GetCurrentUserName();

	/** 
		Get the free space information for the given file drive.
	*/
	static FileDriveInfo GetFileDriveInfo(const QString& fileDrivePath);

	/**
		Get compiler specific variable.
		Please note, that this variable depends only on compiler time state and cannot be set by application.
		To use 'logical value' of variable you should use \c GetVariableValue.
	*/
	static QString GetCompilerVariable(const QString& varName);

	/**
		Set some user specific variables to override the generated by compiler.
		\param	compilerMode	typically is 'Debug' or 'Release'.
		\param	compilerName	code of compiler, e.g. 'VC12' or 'GCC'.
		\param	platformCode	suffix used typically to differentiate 32 and 64 bit mode - empty for 32 bit and 'x64' for 64 bit mode.
	*/
	static void SetUserVariables(const QString& compilerMode, const QString& compilerName, const QString& platformCode);

	/**
		Convert a mapped network path to UNC representation.
	*/
	static QString ConvertNetworkPathToUnc(const QString& localPath);

private:
	static QString s_compilerMode;
	static QString s_compilerName;
	static QString s_platformCode;
};


} // namespace istd


#endif // !istd_CSystem_included


