echo Creating installation scripts...

"%ACFDIR%/Bin/Debug%COMPILER_EXT%/Acf.exe" Install/InternalParts/CreateScripts.arx -config $(ACFSLNDIR)/Config/Core.xpc -input Install -output Install/TempExcl
