OUTPUT_NAME=iqt

# include the basic definitions for this module
include ../../../Impl/Make/Makefile.settings

# include the definitions for Qt compilation
include ../../../Impl/Make/MakefileQt.settings

HAS_UI = 0

# include the basic rules for creation this module
include ../../../Impl/Make/Makefile.rules

# include the rules for compilation of Qt related classes
include ../../../Impl/Make/MakefileQt.rules