#ifndef iqtprm_CComposedParamsSetGuiComp_included
#define iqtprm_CComposedParamsSetGuiComp_included


// Qt includes
#include <QWidget>

#include "istd/CString.h"

#include "imod/TSingleModelObserverBase.h"

#include "iprm/IParamsSet.h"

#include "iqt/IGuiObject.h"
#include "iqt/TGuiObserverWrap.h"
#include "iqt/TGuiComponentBase.h"

#include "iqt2d/ISceneExtender.h"

#include "iqtprm/iqtprm.h"


namespace iqtprm
{


class CComposedParamsSetGuiComp:
			public iqt::TGuiObserverWrap<iqt::TGuiComponentBase<QWidget>, imod::TSingleModelObserverBase<iprm::IParamsSet> >,
			public iqt2d::ISceneExtender
{
	Q_OBJECT

public:
	typedef iqt::TGuiObserverWrap<iqt::TGuiComponentBase<QWidget>, imod::TSingleModelObserverBase<iprm::IParamsSet> > BaseClass;

	I_BEGIN_COMPONENT(CComposedParamsSetGuiComp);
		I_REGISTER_INTERFACE(imod::IObserver);
		I_REGISTER_INTERFACE(imod::IModelEditor);
		I_REGISTER_INTERFACE(iqt2d::ISceneExtender);
		I_ASSIGN_MULTI_0(m_editorsCompPtr, "Editors", "List of GUI's for parameters edition", true);
		I_ASSIGN_MULTI_0(m_guisCompPtr, "Editors", "List of GUI's for parameters edition", true);
		I_ASSIGN_MULTI_0(m_observersCompPtr, "Editors", "List of GUI's for parameters edition", true);
		I_ASSIGN_MULTI_0(m_extendersCompPtr, "Editors", "List of GUI's for parameters edition", false);
		I_ASSIGN_MULTI_0(m_idsAttrPtr, "Ids", "List of parameter ID's according to defined editors", true);
		I_ASSIGN_MULTI_0(m_namesAttrPtr, "Names", "List of of gui names", false);
		I_ASSIGN(m_useHorizontalLayoutAttrPtr, "UseHorizontalLayout", "Use horizontal layout", true, false);
		I_ASSIGN(m_showAllShapesAttrPtr, "ShowAllShapes", "If true all shapes, also generated by inactive GUI, will be shown", true, false);
		I_ASSIGN(m_designTypeAttrPtr, "DesignType", "Type of design:\n* 0 - simple\n* 1 - tool box\n* 2 - tab", true, false);
I_END_COMPONENT;

	CComposedParamsSetGuiComp();

	// reimplemented (imod::IModelEditor)
	virtual void UpdateModel() const;
	virtual void UpdateEditor();

	// reimplemented (imod::IObserver)
	virtual bool OnAttached(imod::IModel* modelPtr);
	virtual bool OnDetached(imod::IModel* modelPtr);

	// reimplemented (iqt::CGuiComponentBase)
	virtual void OnGuiCreated();

	// reimplemented (iqt2d::ISceneExtender)
	virtual void AddItemsToScene(iqt2d::ISceneProvider* providerPtr, int flags);
	virtual void RemoveItemsFromScene(iqt2d::ISceneProvider* providerPtr);

protected:
	void AttachToScene(iqt2d::ISceneProvider* providerPtr, int flags);
	void DetachFromScene(iqt2d::ISceneProvider* providerPtr);

protected slots:
	void OnEditorChanged(int index);

private:
	I_MULTIREF(imod::IModelEditor, m_editorsCompPtr);
	I_MULTIREF(iqt::IGuiObject, m_guisCompPtr);
	I_MULTIREF(imod::IObserver, m_observersCompPtr);
	I_MULTIREF(iqt2d::ISceneExtender, m_extendersCompPtr);
	I_MULTIATTR(istd::CString, m_idsAttrPtr);
	I_MULTIATTR(istd::CString, m_namesAttrPtr);
	I_ATTR(bool, m_useHorizontalLayoutAttrPtr);
	I_ATTR(bool, m_showAllShapesAttrPtr);
	I_ATTR(int, m_designTypeAttrPtr);

	int m_currentGuiIndex;

	typedef std::map<iqt2d::ISceneProvider*, int> ConnectedSceneFlags;	// maps connected scene provider to connection flags
	ConnectedSceneFlags m_connectedSceneFlags;
};


} // namespace iqtprm


#endif // !iqtprm_CComposedParamsSetGuiComp_included


