#ifndef iqtprm_CComposedParamsSetGuiComp_included
#define iqtprm_CComposedParamsSetGuiComp_included


// STL includes
#include <set>

// ACF includes
#include "istd/CString.h"

#include "iser/IFileLoader.h"

#include "iprm/IParamsSet.h"

#include "iqtgui/TDesignerGuiObserverCompBase.h"

#include "iqt2d/ISceneExtender.h"

#include "iqtprm/iqtprm.h"
#include "iqtprm/Generated/ui_CComposedParamsSetGuiComp.h"


namespace iqtprm
{


class CComposedParamsSetGuiComp:
			public iqtgui::TDesignerGuiObserverCompBase<Ui::CComposedParamsSetGuiComp, iprm::IParamsSet>,
			public iqt2d::ISceneExtender
{
	Q_OBJECT

public:
	typedef iqtgui::TDesignerGuiObserverCompBase<Ui::CComposedParamsSetGuiComp, iprm::IParamsSet> BaseClass;

	I_BEGIN_COMPONENT(CComposedParamsSetGuiComp);
		I_REGISTER_INTERFACE(iqt2d::ISceneExtender);
		I_ASSIGN_MULTI_0(m_editorsCompPtr, "Editors", "List of GUI's for parameters edition", true);
		I_ASSIGN_TO(m_guisCompPtr, m_editorsCompPtr, true);
		I_ASSIGN_TO(m_observersCompPtr, m_editorsCompPtr, true);
		I_ASSIGN_TO(m_extendersCompPtr, m_editorsCompPtr, false);
		I_ASSIGN(m_paramsLoaderCompPtr, "ParamsLoader", "Loader for the parameter set", false, "ParamsLoader");
		I_ASSIGN_MULTI_0(m_idsAttrPtr, "Ids", "List of parameter ID's according to defined editors", true);
		I_ASSIGN_MULTI_0(m_namesAttrPtr, "Names", "List of of gui names", false);
		I_ASSIGN(m_useHorizontalLayoutAttrPtr, "UseHorizontalLayout", "Use horizontal layout", true, false);
		I_ASSIGN(m_showAllShapesAttrPtr, "ShowAllShapes", "If true all shapes, also generated by inactive GUI, will be shown", true, false);
		I_ASSIGN(m_designTypeAttrPtr, "DesignType", "Type of design:\n* 0 - simple\n* 1 - tool box\n* 2 - tab", true, false);
	I_END_COMPONENT;

	CComposedParamsSetGuiComp();

	// reimplemented (imod::IModelEditor)
	virtual void UpdateModel() const;
	virtual void UpdateEditor(int updateFlags = 0);

	// reimplemented (imod::IObserver)
	virtual bool OnAttached(imod::IModel* modelPtr);
	virtual bool OnDetached(imod::IModel* modelPtr);

	// reimplemented (iqtgui::CGuiComponentBase)
	virtual void OnGuiCreated();
	virtual void OnGuiDestroyed();

	// reimplemented (iqt2d::ISceneExtender)
	virtual void AddItemsToScene(iqt2d::ISceneProvider* providerPtr, int flags);
	virtual void RemoveItemsFromScene(iqt2d::ISceneProvider* providerPtr);

protected:
	void AttachToScene(iqt2d::ISceneProvider* providerPtr, int flags);
	void DetachFromScene(iqt2d::ISceneProvider* providerPtr);

protected slots:
	void OnEditorChanged(int index);
	void on_LoadParamsButton_clicked();
	void on_SaveParamsButton_clicked();

private:
	I_MULTIREF(imod::IModelEditor, m_editorsCompPtr);
	I_MULTIREF(iqtgui::IGuiObject, m_guisCompPtr);
	I_MULTIREF(imod::IObserver, m_observersCompPtr);
	I_MULTIREF(iqt2d::ISceneExtender, m_extendersCompPtr);
	I_REF(iser::IFileLoader, m_paramsLoaderCompPtr);
	I_MULTIATTR(istd::CString, m_idsAttrPtr);
	I_MULTIATTR(istd::CString, m_namesAttrPtr);
	I_ATTR(bool, m_useHorizontalLayoutAttrPtr);
	I_ATTR(bool, m_showAllShapesAttrPtr);
	I_ATTR(int, m_designTypeAttrPtr);

	typedef std::set<imod::IModelEditor*> ConnectedEditors;
	ConnectedEditors m_connectedEditors;

	int m_currentGuiIndex;

	typedef std::map<iqt2d::ISceneProvider*, int> ConnectedSceneFlags;	// maps connected scene provider to connection flags
	ConnectedSceneFlags m_connectedSceneFlags;
};


} // namespace iqtprm


#endif // !iqtprm_CComposedParamsSetGuiComp_included


