#ifndef iqtprm_CExtComposedParamsSetGuiComp_included
#define iqtprm_CExtComposedParamsSetGuiComp_included


// Qt includes
#include <QtCore/QString>
#include <QtCore/QSet>

// ACF includes
#include <imod/TSingleModelObserverBase.h>
#include <ibase/TModelObserverCompWrap.h>
#include <iprm/IParamsSet.h>
#include <iqtgui/TGuiObserverWrap.h>
#include <iqtgui/CComposedGuiComp.h>
#include <iqt2d/IViewExtender.h>
#include <iqtprm/iqtprm.h>


namespace iqtprm
{


/**
	New version of parameter set UI based on standard multi page UI concept.
*/
class CExtComposedParamsSetGuiComp:
			public ibase::TModelObserverCompWrap<
						iqtgui::TGuiObserverWrap<
									iqtgui::CComposedGuiComp, imod::TSingleModelObserverBase<iprm::IParamsSet> > >,
			public iqt2d::IViewExtender
{
public:
	typedef ibase::TModelObserverCompWrap<
				iqtgui::TGuiObserverWrap<
							iqtgui::CComposedGuiComp, imod::TSingleModelObserverBase<iprm::IParamsSet> > > BaseClass;

	I_BEGIN_COMPONENT(CExtComposedParamsSetGuiComp);
		I_REGISTER_INTERFACE(iqt2d::IViewExtender);
		I_REGISTER_INTERFACE(imod::IModelEditor);
		I_ASSIGN_MULTI_0(m_editorsCompPtr, "Editors", "List of GUI's for parameters edition", true);
		I_ASSIGN_TO(m_observersCompPtr, m_editorsCompPtr, true);
		I_ASSIGN_TO(m_extendersCompPtr, m_editorsCompPtr, false);
		I_ASSIGN_MULTI_0(m_idsAttrPtr, "Ids", "List of parameter ID's according to defined editors, if ID equals '*' then the observed parameter set will be used, if it is empty than only GUI will be shown, but no parameter will be connected", true);
		I_ASSIGN(m_showAllShapesAttrPtr, "ShowAllShapes", "If true all shapes, also generated by inactive GUI, will be shown", true, false);
	I_END_COMPONENT;

	// reimplemented (imod::IModelEditor)
	virtual void UpdateEditor(const istd::IChangeable::ChangeSet& changeSet);
	virtual void SetReadOnly(bool state);

	// reimplemented (iqtgui::CGuiComponentBase)
	virtual void OnGuiCreated();
	virtual void OnGuiDestroyed();

	// reimplemented (iqt2d::IViewExtender)
	virtual void AddItemsToScene(iqt2d::IViewProvider* providerPtr, int flags);
	virtual void RemoveItemsFromScene(iqt2d::IViewProvider* providerPtr);

protected:
	void AttachToScene(iqt2d::IViewProvider* providerPtr, int flags);
	void DetachFromScene(iqt2d::IViewProvider* providerPtr);

	// reimplemented (iqtgui::CMultiPageGuiCompBase)
	virtual void CreatePages();
	virtual void OnPageChanged(int widgetIndex);

	// reimplemented (iqtgui::TGuiObserverWrap)
	virtual void OnGuiModelAttached();
	virtual void OnGuiModelDetached();
	virtual void UpdateModel() const;

private:
	I_MULTIREF(imod::IModelEditor, m_editorsCompPtr);
	I_MULTIREF(imod::IObserver, m_observersCompPtr);
	I_MULTIREF(iqt2d::IViewExtender, m_extendersCompPtr);
	I_MULTIATTR(QByteArray, m_idsAttrPtr);
	I_MULTITEXTATTR(m_namesAttrPtr);
	I_ATTR(bool, m_showAllShapesAttrPtr);

	typedef QMap<imod::IModelEditor*, bool> ConnectedEditorsMap;
	ConnectedEditorsMap m_connectedEditorsMap;

	typedef QMap<iqt2d::IViewProvider*, int> ConnectedSceneFlags; // maps connected scene provider to connection flags
	ConnectedSceneFlags m_connectedSceneFlags;
};


} // namespace iqtprm


#endif // !iqtprm_CExtComposedParamsSetGuiComp_included


